function matlabbatch = create_vdm(matlabbatch,te,pd,epi,sess_count) 
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.data.presubphasemag.phase = {te};
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.data.presubphasemag.magnitude = {pd};
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.et = [4.92 7.38];
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.maskbrain = 1;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.blipdir = -1;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.tert = 63.24;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.epifm = 0;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.ajm = 0;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.uflags.method = 'Mark3D';
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.uflags.fwhm = 10;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.uflags.pad = 0;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.uflags.ws = 1;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.mflags.template = {'C:\Toolboxes\spm12\toolbox\FieldMap\T1.nii'};
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.mflags.fwhm = 5;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.mflags.nerode = 2;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.mflags.ndilate = 4;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.mflags.thresh = 0.5;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.defaults.defaultsval.mflags.reg = 0.02;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.session.epi = {epi};
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.matchvdm = 1;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.sessname = 'session';
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.writeunwarped = 1;
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.anat = '';
matlabbatch{sess_count}.spm.tools.fieldmap.calculatevdm.subj.matchanat = 0;
end